

chunks = {0xd8: "SOI",
          0xc0: "SOF",
          0xc2: "SOF2",
          0xc4: "DHT",
          0xdb: "DQT",
          0xdd: "DRI",
          0xda: "SOS",
          0xd0: "RST",
          0xd1: "RST",
          0xd2: "RST",
          0xd3: "RST",
          0xd4: "RST",
          0xd5: "RST",
          0xd6: "RST",
          0xd7: "RST",
          0xe0: "APP0",
          0xe1: "APP1",
          0xe2: "APP2",
          0xe3: "APP3",
          0xec: "APP12",
          0xed: "APP13",
          0xee: "APP14",
          0xfe: "COM",
          0xd9: "EOI"}
